version: '2.1'

services:
  db:
    image: postgres
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  web:
    build: .
    command: sh runserver.sh
    volumes:
      - .:/code
    environment:
      DATABASE_URL: "postgresql://db:5432/expenses?user=admin&password=admin1234"
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy